### ISSUE TITLE
SplFileObject::__construct(./modules/commerce_demo/data/demo_data.csv): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by mglaman** [mglaman/commerce_demo#5]

**Comment by jpdaut** [comment]
I believe the below should fix this.   (adding 'contrib' in the source path in this yml file, because Composer installs modules in web/modules/contrib by default)

migrate_plus.migration_group.commerce_demo.yml :
langcode: en
status: true
dependencies: {  }
id: commerce_demo
label: 'Commerce Demo'
description: 'Imports products into the site.'
source_type: 'CSV Files'
module: null
shared_configuration:
  source:
    path: ./modules/contrib/commerce_demo/data/demo_data.csv
    header_row_count: 1

**Comment by mglaman** [comment]
This was committed. Probably broke build.
